### Notizen ### 

- Umgang Längsschnitt (Stichwort: sampling weights)
- Fehelde Werte mit Werten aus einem späteren Zeitpunkt auffüllen, so gemacht bei Big 5, sonst aber nicht: Wo kommt es noch in Frage?
- Noten z standardisieren?
- Current study phase = MZP2; Was, wenn Personanen da schon kein Lehramt mehr studieren. Fachwechsler*innen filtern? Oder egal, weil am 
  Ende in der Variable Dropout explizit nach Lehramt geschaut wird und es explizit egal ist, wann der Abbruch (inkl. Wechsel) passiert ist 
  (Sonst wäre es Abbruch zwischen MZP 2 und 3, oder?) ...aber eine gute Integration in einem anderen Fach ist inhaltlich uninteressant
- LPA, LCA oder Mixture Model (in den R-Skripten sind Paper und Tutorials verlinkt, Paper von J. Bauer verfügt auch über R-Skripte im Anhang)
- Stichprbendefinition: Einfach Endprodukt berichten, oder Ausschlüsse
- Packages geben Bayes Faktor nicht aus, mit Shiny App keinen Erfolg https://robert-fox.shinyapps.io/BF_cmP_Calculator/ (Wie berechnen?)
- Benutzen alle LCA (LPA) Maximum Likelihood Schätze (beziehungsweise ist der EM-Algorithmus ein ML-Schätzer (Hintegrund: In Präreg. Nutzung von MLE genannt).

- Problem: Fast keine Daten nur Nutzung von Lerngelegenheiten - Missings bei über 90%





### Abweichungen von der Praeregistrierung ### 

## Andere Items genutzt
- Age of enrollment
- Type of higher education inst



## Code Check 19.1.2024

## `par_edu` vs. `par_ocu`
Du hattest dich ja gewundert, warum Studierende oftmals Eltern ohne Hochschulabschluss haben (`par_edu`), die Eltern dann aber keine mixed oder working class sind (`par_ocu`): Vielleicht ist deine Um codierung in `par_ocu` nicht so optimal. Du machst

```{r}
  dplyr::mutate(par_ocu = case_when((t731403_g8 >= 8 | t731453_g8 >= 8) ~ 1,    
                                    (t731403_g8 <= 7 | t731453_g8 <= 7) ~ 2,
                                    TRUE ~ as.numeric(NA)))
                                    # 1 = working class, 
                                    # 2 = mixed and service class
```

Dabei ist beispielsweise die Ausprägung 4 (="Angestellte der ausführenden nicht‐manuellen Klasse mit gering qualifizierten Routinetätigkeiten")laut Wikipedia beispielsweise eine Kassiererin. Wäre das nicht auch working class? D.h. woher hast du die Unterscheidung in working class und mixed + service class? Gibt es hier vielleicht eine gute Quelle?

